### ISSUE TITLE
Support for variadic SET command

### ISSUE THREAD

**Issue by shanipribadi** [aerospike/skyhook#10]
Redis SET command also support variadic arguments
```
 SET key value [EX seconds|PX milliseconds|EXAT timestamp|PXAT milliseconds-timestamp|KEEPTTL] [NX|XX] [GET] 
```
https://redis.io/commands/set

note from the page mention that
```Note: Since the SET command options can replace SETNX, SETEX, PSETEX, GETSET, it is possible that in future versions of Redis these commands will be deprecated and finally removed.```

**Comment by rbotzer** [comment]
Good idea. We'll look into implementing this.
