### ISSUE TITLE
compatibility of SET, INCR, INCRBYFLOAT, GET

### ISSUE THREAD

**Issue by shanipribadi** [aerospike/skyhook#14]
Redis INCR and INCRBYFLOAT (and the DECR variants) actually operates on numbers stored as ASCII strings

This way, GET always returns values as string type
and INCR and INCRBYFLOAT can operate on string that can be parsed as numbers,
providing some compatibility between them.

for INCR, ``` The string stored at the key is interpreted as a base-10 64 bit signed integer to execute the operation.```
https://redis.io/commands/incr

and for INCRBYFLOAT ```double precision floating point number```
https://redis.io/commands/incrbyfloat

right now Skyhook stores values in SET command into different Aerospike type depending on whether they are parsable as numbers or not. Also INCR is stored in Aerospike as LongValue and INCRBYFLOAT is stored in Aerospike as DoubleValue.
Hence there are different in behaviours between Skyhook and Redis.

**Comment by rbotzer** [comment]
Shani, forget the way Skyhook stores values in Aerospike for a moment - what is the problem you are seeing in your Redis application? 

Can you provide some code to show the problem?

**Comment by rbotzer** [comment]
@reugn, talked to Shani and the issue is that he wants to be able to increment a float value with an integer, or an integer value with a float, and always return the value associated with the key as a numeric string with the appropriate value representation.
