### ISSUE TITLE
consistency semantics for skyhook

### ISSUE THREAD

**Issue by romange** [aerospike/skyhook#3]
Redis is famously single-threaded, thus providing strict serializability guarantees for multi-key operations. 
What are the guarantees in Skyhook? Are multi-key operations atomic? Are they (strictly) serializable?

**Comment by reugn** [comment]
Hi. Skyhook doesn't guarantee atomicity/strict serializability for multi-key operations.

**Comment by romange** [comment]
Thanks for the quick reply!
